### ISSUE TITLE
Tablespace Entity

### ISSUE THREAD

**Issue by xsist10** [xsist10/cadfael#24]
To support bugfix #19, we need to add a new Tablespace Entity

# TODO

- [x] Add new TableSpace entity
- [x] Add Factory support to extract and build them
- [x] Attach TableSpace to appropriate Table entities
